### PR TITLE
v0.8.1

### PR DESCRIPTION
**Pull request by kandersolar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Review by wholmgren — APPROVED** [review]
might as well add the min python version while you're here.

**Comment by kandersolar** [comment]
@conda-forge-admin, please rerender

**Comment by wholmgren** [comment]
perhaps we can satisfy the license identifier complaint by changing it to `BSD-3-Clause` (note the extra hyphen).

https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions

**Comment by kandersolar** [comment]
@wholmgren is [this log output](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=258352&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=1027) sufficient to be able to check the "Ensured the license file is being packaged." box, or is there a build artifact somewhere I can examine?

**Comment by wholmgren** [comment]
that's more than I've ever done to check! I've just relied on checking the license file name and the linter.

**Pull request merged**
