### PR TITLE
v0.9.2: include setuptools_scm in host

### PR DESCRIPTION
**Pull request by kandersolar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* ~[ ] Reset the build number to `0` (if the version changed)~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Adding `setuptools_scm` to the `host` requirements, per discussion in #31.  Also sorry for the "review request" noise; it doesn't seem possible to disable that ahead of time (if it is, let me know!).

### CODE REVIEW

**Comment by kandersolar** [comment]
@conda-forge-admin, please rerender

**Comment by kandersolar** [comment]
The logs seem promising; compare `Successfully installed pvlib-0.0.0` in the [previous log](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=554699&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=764) with `Successfully installed pvlib-0.9.2` in [this one](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=554734&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=769), and similar elsewhere in the logs.  @wholmgren is that convincing enough to hit merge here?

This docs page also seems to indicate that we're doing the right thing now: https://conda-forge.org/docs/maintainer/knowledge_base.html#using-setuptools-scm

**Comment by wholmgren** [comment]
Go for it

**Comment by kandersolar** [comment]
FYI that seems to have done the trick; the new build (`pyhd8ed1ab_1`) correctly reports `pvlib.__version__ == '0.9.2'`.

**Pull request merged**
