### PR TITLE
update version and hash for 0.4.2 maybe with circleci now working

### PR DESCRIPTION
**Pull request by wholmgren**

### CODE REVIEW

**Comment by jakirkham** [comment]
So you can enable CircleCI builds on your [fork]( https://circleci.com/gh/wholmgren/pvlib-python-feedstock ). That should be an effective workaround to get something building on CircleCI again.

**Comment by wholmgren** [comment]
Thanks for the update @jakirkham. I would rather not enable CircleCI on my fork because it wants access to all of my private repositories and it sounds like they are not particularly security conscious. I suppose a workaround for the workaround is to create a second github account...

**Comment by jakirkham** [comment]
I wouldn't go to that much trouble unless you need this built ASAP. CircleCI is working on a better long term solution than the workaround proposed above.

**Comment by wholmgren** [comment]
Ok, thanks!

**Pull request closed without merging**
