### PR TITLE
bump to 0.4.1, remove pytest-runner

### PR DESCRIPTION
**Pull request by wholmgren**

### CODE REVIEW

**Comment by jakirkham** [comment]
Please [re-render](https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock) with `conda-smithy` version `1.3.2`.

**Comment by jakirkham** [comment]
Thanks.

**Comment by wholmgren** [comment]
Thanks. Was about to ping for help on why the circleci tests were mysteriously failing. Appveyor and travis worked last night, and I'll merge when they pass.

**Comment by jakirkham** [comment]
Yep, there have been a lot of fixes an improvements in 1.x. The most recent release is essential for compiled packages on Travis CI.

Just FYI we have a lot of re-renderings ATM so the CIs may be a bit slow. Expect it should pick up later in the day.

**Pull request merged**
